version: '3.8'

services:
  smart-note-collector:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - notes_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 可选：添加 Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: smart-note-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - smart-note-collector
    restart: unless-stopped
    profiles:
      - with-nginx

volumes:
  # 命名卷用于数据持久化
  note_data:
    driver: local
  note_uploads:
    driver: local
